name: JM Download v2
on:
  workflow_dispatch:
    inputs:
      id:
        description: album id
        required: true
        type: string
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install jmcomic -q
      - run: python3 -c "from jmcomic import download_album; download_album('${{ github.event.inputs.id }}')"
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: ./18comic/
